### ISSUE TITLE
关于AnchorCheck出现报错

### ISSUE THREAD

**Issue by Terry-Uv** [YINYIPENG-EN/yolov7_torch#3]
作者大大你好，能看到在v7上有剪枝的版本实在是非常惊喜。**请问在`prunmodel.py`第`21~30`行的代码目的是什么呢？**

# Compatibility updates
    for m in model.modules():  # 取出每一层
        if type(m) in [nn.Hardswish, nn.LeakyReLU, nn.ReLU, nn.ReLU6, nn.SiLU, Detect, Model]:
            m.inplace = inplace  # pytorch 1.7.0 compatibility
            if type(m) is Detect:  # 判断是否为目标检测
                if not isinstance(m.anchor_grid, list):  # new Detect Layer compatibility
                    delattr(m, 'anchor_grid')
                    setattr(m, 'anchor_grid', [torch.zeros(1)] * m.nl)
        elif type(m) is Conv:  # 卷积层
            m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibilit

在这里如果是Detect层的话，我们就把层级里的anchor_grid给替换为list了，而且是全零的？这是为什么呢？

在经过这几行代码操作之后，今晚我尝试性跑了一下你的代码，剪枝成功后进行train，出现如下报错：

autoanchor: Analyzing anchors... Traceback (most recent call last):
  File "/home/usr1/yolov7_prune/train.py", line 551, in <module>
    train(hyp, opt, device)
  File "/home/usr1/yolov7_prune/train.py", line 268, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "/home/usr1/yolov7_prune/utils/autoanchor.py", line 40, in check_anchors
    anchors = m.anchor_grid.clone().cpu().view(-1, 2)  # current anchors
AttributeError: 'list' object has no attribute 'clone'

替换为了List，导致无法做原代码的autoanchor里的check_anchors了。
我有思考过将list里的各个张量做deepcopy，但是貌似clone()支持梯度回溯，而deepcopy并不具有这样的功能（而且grid是一串list的话，训练部分还能继续训练吗......）

希望大佬不吝赐教！

_Btw,其实剪枝后train就是fine\_tune来恢复精度是嘛？需要多少epoch+batchsize合适呢？_

**Comment by YINYIPENG-EN** [comment]
21~30行代码：这一部分主要是确保Detect 中的 anchor_grid 属性与当前版本的PyTorch兼容。anchor_grid 是用来存储先验框用的，在较新版本的中的Detect中，anchor_grid 属性被定义为一个列表，其中每个元素都是形状为 (1, num_anchors, 2) 的张量。这些张量包含了不同尺度下的先验框坐标和宽高信息。在旧版本的 Detect 模块中，anchor_grid 属性可能被定义为其他类型的对象（例如一个张量）。如果是这种情况，那么上述代码块就会删除该属性并重新定义为一个包含正确尺寸张量的列表。这样可以确保在新版本的 Detect 模块中，所有的 anchor_grid 属性都符合要求。

**Comment by YINYIPENG-EN** [comment]
致于你说的剪枝问题，我并没有遇到像你说的这样的报错，还希望可以提供更多的信息帮助你排查问题，微调训练恢复精度至于用多少epoch和batchsize,这个需要根据自己的设备情况以及数据集来尝试。

**Comment by Terry-Uv** [comment]
> 21~30行代码：这一部分主要是确保Detect 中的 anchor_grid 属性与当前版本的PyTorch兼容。anchor_grid 是用来存储先验框用的，在较新版本的中的Detect中，anchor_grid 属性被定义为一个列表，其中每个元素都是形状为 (1, num_anchors, 2) 的张量。这些张量包含了不同尺度下的先验框坐标和宽高信息。在旧版本的 Detect 模块中，anchor_grid 属性可能被定义为其他类型的对象（例如一个张量）。如果是这种情况，那么上述代码块就会删除该属性并重新定义为一个包含正确尺寸张量的列表。这样可以确保在新版本的 Detect 模块中，所有的 anchor_grid 属性都符合要求。

这样，原来是代码新旧版本的问题，我昨晚在查loss.py的计算时候也发现了版本不同OvO
所以我对代码进行了一下大胆修改，就是将上边21~30行的代码里进行了删除：
```
for m in model.modules():  # 取出每一层
    if type(m) in [nn.Hardswish, nn.LeakyReLU, nn.ReLU, nn.ReLU6, nn.SiLU, Detect, Model]:
        m.inplace = inplace  # pytorch 1.7.0 compatibility
        # if type(m) is Detect:  # 判断是否为目标检测
            # if not isinstance(m.anchor_grid, list):  # new Detect Layer compatibility
                # delattr(m, 'anchor_grid')
                # setattr(m, 'anchor_grid', [torch.zeros(1)] * m.nl)
    elif type(m) is Conv:  # 卷积层
        m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibilit
```
发现报错消失，是能fine-tune进行恢复训练的，在训完一定epoch后，直接使用detect.py的attempt_load（当然是去除了fuse的版本）也是可以检测出来结果的。
但我又遇到了一个新的问题：无法load_state_dict。

因为我需要对模型做后续量化等的优化步骤，需要load_state_dict方式载入，即使用如下代码：
```
    model = Model(opt.cfg).to(torch.device('cpu')).eval()
    weights = opt.weights[0]
    state_dict = torch.load(weights, map_location=torch.device('cpu'))
    model.load_state_dict(state_dict,strict=False)
（True/False都试过了，均抛异常）
```

但抛如下异常：
```
File "/home/usr1/yolov7-detect/models/yolo.py", line 28, in get_model
    model.load_state_dict(state_dict,strict=False)
  File "/home/usr1/pytorch/src/catch/venv/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for model.0.conv.weight: copying a param with shape torch.Size([2, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3]).
        size mismatch for model.0.bn.weight: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for model.0.bn.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for model.0.bn.running_mean: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([32]).
        ..............剪枝操作的层都抛异常了..................
```
大概意思，我猜应该就是剪枝导致的一些size mismatch了。请问这种问题该如何解决呢？0.0

**Comment by Terry-Uv** [comment]
BTW，忘记说一点，我对大佬项目里还进行了一个改动，就是prune最后save的时候，保存的是mdoel.float()而非原本的model.half()，但我感觉这只是保存上精度的问题，这应该非mismatch成因，mismatch成因很明显应该就是剪枝了（说回来这不正应该是剪枝的本意吗hh）
再进行了一些探究，但网上资料大多“pop相应层”、“对于某个layer直接不加载”，始终苦恼，还希望大大能不吝解惑。
